# ---
# jupyter:
#   jupytext:
#     formats: py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.16.4
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Release watermark and generated-label audit
#
# The audit is non-destructive. OOXML VML/DrawingML, manuscript text, and PDF
# byte streams are checked for watermark-like labels. Removal is not attempted
# when no matched object exists.

# %%
from __future__ import annotations
from release_paths import release_path as _release_path

import json
import re
import zipfile
from pathlib import Path

ROOT = Path(str(_release_path('analysis')))
DELIVERY = ROOT / "delivery"
WATERMARK_LABELS = ("draft", "confidential", "sample", "do not copy")
GENERATED_LABELS = (
    "ai generated", "generated by chatgpt", "generated by openai", "gemini generated",
)


def docx_hits(path):
    hits = []
    with zipfile.ZipFile(path) as archive:
        bad = archive.testzip()
        if bad:
            hits.append({"file": str(path.relative_to(ROOT)), "part": bad, "token": "zip_crc_error"})
        for name in archive.namelist():
            if not name.endswith((".xml", ".rels")):
                continue
            text = archive.read(name).decode("utf-8", errors="ignore").lower()
            for match in re.finditer(r"<v:textpath[^>]*\bstring=[\"']([^\"']+)[\"']", text):
                label = match.group(1).strip()
                if any(token in label for token in WATERMARK_LABELS + GENERATED_LABELS):
                    hits.append({"file": str(path.relative_to(ROOT)), "part": name, "token": label})
            if re.search(r"(?:name|id|title|descr)=[\"'][^\"']*watermark", text):
                hits.append({"file": str(path.relative_to(ROOT)), "part": name, "token": "watermark_attribute"})
            for token in GENERATED_LABELS:
                if token in text:
                    hits.append({"file": str(path.relative_to(ROOT)), "part": name, "token": token})
    return hits


hits = []
docx_files = sorted(DELIVERY.rglob("*.docx"))
for path in docx_files:
    hits.extend(docx_hits(path))

for path in sorted((ROOT / "manuscript").glob("*.md")):
    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    for token in GENERATED_LABELS:
        if token in text:
            hits.append({"file": str(path.relative_to(ROOT)), "part": "plain_text", "token": token})

for path in sorted(DELIVERY.rglob("*.pdf")):
    text = path.read_bytes().lower()
    for token in GENERATED_LABELS + ("confidential watermark", "draft watermark"):
        if token.encode() in text:
            hits.append({"file": str(path.relative_to(ROOT)), "part": "pdf_bytes", "token": token})

payload = {
    "mode": "non-destructive report",
    "docx_files_checked": len(docx_files),
    "pdf_files_checked": len(list(DELIVERY.rglob("*.pdf"))),
    "markdown_files_checked": len(list((ROOT / "manuscript").glob("*.md"))),
    "watermark_labels": WATERMARK_LABELS,
    "generated_labels": GENERATED_LABELS,
    "watermark_like_hits": len(hits),
    "hits": hits,
    "removal_performed": False,
    "reason": "No matched watermark-like object; destructive OOXML removal was unnecessary." if not hits else "Matched labels require manual adjudication before removal.",
    "passed": not hits,
}
(ROOT / "outputs" / "WATERMARK_RELEASE_AUDIT.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
print(json.dumps(payload, indent=2))
if hits:
    raise SystemExit(1)
